adding april 2024 community call blog post
m-lab/website pull request #797
Opened 2024-03-26 13:10 UTC by laiyi-ohlsen

2024-03-27 20:31 UTC, georgiamoon commented on _posts/blog/2024-03-25-apr24-community-call.md
> +title: "Measuring Internet Quality from the User's Perspective"
Measuring the Quality of an Individual's Connection

2024-03-27 20:32 UTC, georgiamoon commented on _posts/blog/2024-03-25-apr24-community-call.md
> +## Metrics for Measuring Your Internet's Quality
Metrics for Measuring the Quality of an Individual Connection

2024-03-27 20:33 UTC, georgiamoon commented on _posts/blog/2024-03-25-apr24-community-call.md
> +Internet Quality Barometer is generously supported by an [Internet Society Research Grant](https://www.isocfoundation.org/2024/01/announcing-our-2023-research-grantee-cohort-14-projects-examining-the
"Internet Society Foundation Research Grant"

2024-03-27 20:33 UTC, georgiamoon requested changes
Made some suggested edits, but after that LGTM

2024-03-29 11:43 UTC, laiyi-ohlsen reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/website/797)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @georgiamoon)

___
*[`_posts/blog/2024-03-25-apr24-community-call.md` line 3 at r1](https://reviewable.io/reviews/m-lab/website/797#gh-1541991121:-Nu90QLD5sbd38jbfNGs:b-896fix) ([raw file](https://github.com/m-lab/website/blob/aa17d1a0ffbfe029b7dad0bce2c17d5fe3044803/_posts/blog/2024-03-25-apr24-community-call.md#L3)):*
<details><summary><i>Previously, georgiamoon (georgia bullen) wrote…</i></summary><blockquote>

Measuring the Quality of an Individual's Connection
</blockquote></details>

Done.
___
*[`_posts/blog/2024-03-25-apr24-community-call.md` line 14 at r1](https://reviewable.io/reviews/m-lab/website/797#gh-1541991699:-Nu90QnwCwscvSlik0Y1:b-896fix) ([raw file](https://github.com/m-lab/website/blob/aa17d1a0ffbfe029b7dad0bce2c17d5fe3044803/_posts/blog/2024-03-25-apr24-community-call.md#L14)):*
<details><summary><i>Previously, georgiamoon (georgia bullen) wrote…</i></summary><blockquote>

Metrics for Measuring the Quality of an Individual Connection
</blockquote></details>

Done.
___
*[`_posts/blog/2024-03-25-apr24-community-call.md` line 33 at r1](https://reviewable.io/reviews/m-lab/website/797#gh-1541992873:-Nu90RLr8avR8NJlyy1N:b-896fix) ([raw file](https://github.com/m-lab/website/blob/aa17d1a0ffbfe029b7dad0bce2c17d5fe3044803/_posts/blog/2024-03-25-apr24-community-call.md#L33)):*
<details><summary><i>Previously, georgiamoon (georgia bullen) wrote…</i></summary><blockquote>

"Internet Society Foundation Research Grant"
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-29 13:18 UTC, laiyi-ohlsen reviewed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/website/797)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @georgiamoon)



<!-- Sent from Reviewable.io -->

2024-03-29 14:06 UTC, georgiamoon approved these changes

2024-03-29 14:07 UTC, merged